WebApp/Controllers/CartController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Polly.CircuitBreaker;
using WebMVC.Services;
using WebMVC.ViewModels;

namespace WebMVC.Controllers
{
    public class CartController : Controller
    {
        private readonly IBasketService _basketSvc;
        private readonly ICatalogService _catalogSvc;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;

        public CartController(IBasketService basketSvc, ICatalogService catalogSvc, IIdentityParser<ApplicationUser> appUserParser)
        {
            _basketSvc = basketSvc;
            _catalogSvc = catalogSvc;
            _appUserParser = appUserParser;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var user = _appUserParser.Parse(HttpContext.User);
                var vm = await _basketSvc.GetBasket(user, Request);

                return View(vm);
            }
            catch (BrokenCircuitException)
            {
                // Catch error when Basket.api is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return View();
        }

        public IActionResult AddToCart(CatalogItem productDetails)
        {
            try
            {
                if (productDetails?.Id != null)
                {
                    var cookieBasket = Request.Cookies["basket"];
                    if (cookieBasket != null)
                    {
                        var backetIds = cookieBasket.Split(',').Select(int.Parse).ToList();
                        if (!backetIds.Contains(productDetails.Id))
                        {
                            Response.Cookies.Append("basket", cookieBasket + "," + productDetails.Id);
                        }
                    }
                    else
                    {
                        Response.Cookies.Append("basket", productDetails?.Id.ToString());
                    }
                }

                return RedirectToAction("Index", "Catalog");
            }
            catch (BrokenCircuitException)
            {
                // Catch error when Basket.api is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return RedirectToAction("Index", "Catalog", new { errorMsg = ViewBag.BasketInoperativeMsg });
        }

        private void HandleBrokenCircuitException()
        {
            ViewBag.BasketInoperativeMsg = "Basket Service is inoperative, please try later on. (Business Msg Due to Circuit-Breaker)";
        }

        [HttpPost]
        public IActionResult Detail(int id)
        {
            BasketItem bi = BasketHelper.GetBusketItem(id);
            return View(bi);
        }
    }
}

WebApp/Controllers/OrderController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Services;
using WebMVC.ViewModels;

namespace WebMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderingService _orderSvc;
        private IBasketService _basketSvc;
        private readonly ICatalogService _catalogSvc;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;
        public OrderController(IOrderingService orderSvc, IBasketService basketSvc, IIdentityParser<ApplicationUser> appUserParser, ICatalogService catalogSvc)
        {
            _appUserParser = appUserParser;
            _orderSvc = orderSvc;
            _basketSvc = basketSvc;
            _catalogSvc = catalogSvc;
        }

        public IActionResult Create()
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var vm = _orderSvc.MapUserInfoIntoOrder(user, new Order());
            vm.CardExpirationShortFormat();

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout()
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var cookieBasket = Request.Cookies["basket"];
            if (cookieBasket != null)
            {
                var backetIds = cookieBasket.Split(',').Select(int.Parse).ToList();

                backetIds.ForEach(_id => _catalogSvc.RemoveItemFromStock(_id));
                await _orderSvc.CreateOrder(user, backetIds.ToArray());

                Response.Cookies.Delete("basket");
            }

            return RedirectToAction("Index");
        }


        public IActionResult Cancel(string orderId)
        {
            _orderSvc.CancelOrder(orderId);

            //Redirect to historic list.
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(string orderId)
        {
            var user = _appUserParser.Parse(HttpContext.User);

            var order = await _orderSvc.GetOrder(user, orderId);
            return View(order);
        }

        public async Task<IActionResult> Index(Order item)
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var vm = await _orderSvc.GetMyOrders(user);
            return View(vm);
        }
    }
}

WebApp/Views/Shared/Components/CartList/Default.cshtml
@using WebMVC.ViewModels
@model WebMVC.ViewModels.Basket

@{
    ViewData["Title"] = "My Cart";
}

<div class="container">
    @if (ViewBag.BasketInoperativeMsg != null)
    {
        <br />
        <div class="alert alert-warning" role="alert">
            &nbsp;@ViewBag.BasketInoperativeMsg
        </div>
    }
    else
    {
<article class="esh-basket-titles row">
    <br />
    @if (ViewBag.BasketInoperativeMsg != null)
    {
        <div class="alert alert-warning" role="alert">
            &nbsp;@ViewBag.BasketInoperativeMsg
        </div>
    }

    <section class="esh-basket-title col-3">Product</section>
    <section class="esh-basket-title col-3 hidden-lg-down"></section>
    <section class="esh-basket-title col-2">Price</section>
    <section class="esh-basket-title col-1">Quantity</section>
    @*<section class="esh-basket-title col-1">Cost</section>*@
    <section class="esh-basket-title col-1">Stock</section>
    <section class="esh-basket-title col-1">Details</section>
</article>

        @for (int i = 0; i < Model.Items.Count; i++)
        {
            var item = Model.Items[i];

<article class="esh-basket-items row">
    <section class="esh-basket-item esh-basket-item--middle col-lg-3 hidden-lg-down">
        <img class="esh-basket-image" src="Img/@item.PictureUrl" />
    </section>
    <section class="esh-basket-item esh-basket-item--middle col-3">@item.ProductName</section>
    <section class="esh-basket-item esh-basket-item--middle col-2">$ @item.UnitPrice.ToString("N2")</section>
    <section class="esh-basket-item esh-basket-item--middle col-1">
        <input type="hidden" name="@("quantities[" + i +"].Key")" value="@item.Id" />
        <input type="number" disabled class="esh-basket-input" min="1" name="@("quantities[" + i +"].Value")" value="@item.Quantity" />
    </section>
    @*<section class="esh-basket-item esh-basket-item--middle esh-basket-item--mark col-2">$ @Math.Round(item.Quantity * item.UnitPrice, 2).ToString("N2")</section>*@
    <section class="esh-basket-item esh-basket-item--middle col-1">@item.QuantityStock.ToString()</section>
    <section class="esh-basket-item esh-basket-item--middle col-1">
        <form method="post" id="cartForm" asp-controller="Cart" asp-action="Detail" asp-route-id="@item.Id">
            <input type="submit"
                   class="btn esh-basket-checkout"
                   value="Detail" name="action" />
        </form>
    </section>
</article>
            <br />
        }

        <div class="container">
            <article class="esh-basket-titles esh-basket-titles--clean row">
                <section class="esh-basket-title col-10"></section>
                <section class="esh-basket-title col-2">Total</section>
            </article>

            <article class="esh-basket-items row">
                <section class="esh-basket-item col-10"></section>
                <section class="esh-basket-item esh-basket-item--mark col-2">$ @Model.Total()</section>
            </article>
            <form method="post" id="cartForm" asp-controller="Order" asp-action="Checkout">
                <article class="esh-basket-items row">
                    <section class="esh-basket-item col-7"></section>
                    @*<section class="esh-basket-item col-2">
                            <button class="btn esh-basket-checkout" name="name" value="" type="submit">[ Update ]</button>
                        </section>*@
                    <section class="esh-basket-item col-3">
                        <input type="submit"
                               class="btn esh-basket-checkout"
                               value="Checkout" name="action" />
                    </section>
                </article>
            </form>
        </div>
    }

</div>